### ISSUE TITLE
Extract Reads similar to TE sequences

### ISSUE THREAD

**Issue by juanb001** [hyunhwan-jeong/SalmonTE#38]
Hi,

Would it be possible/easy to incorporate an option where SalmonTE outputs a file containing the reads used to generate the TE count file for each fastq file? I want to manually inspect the reads and see if they really are similar to TE sequences, but I can't do that at the moment.

Thank you!

**Comment by hyunhwaj** [comment]
@juanb001 The function has not been implemented, but I can let you know we are working on it. I will update once we finished it.

Thank you,

Hyun-Hwan Jeong

**Comment by juanb001** [comment]
Thanks for the update; look forward to it!
