### ISSUE TITLE
Cannot run SalmonTE in Snakemake pipeline

### ISSUE THREAD

**Issue by ftabaro** [hyunhwan-jeong/SalmonTE#46]
Hello, 

I get an error about locking the results dir when running SalmonTE in Snakemake pipeline. I forked the repo and got it to run by disabling SalmonTE directory locking. Should I submit a pull request?

**Comment by hyunhwaj** [comment]
@ftabaro,

Can you provide more details about the error to clarify what the exact issue is? 

You can also send a pull request if you figured out how to resolve it. 

Thank you,

Hyun-Hwan Jeong

**Comment by ftabaro** [comment]
Sure! 

So, SalmonTE runs a Snakemake process after starting up. Snakemake creates lock files in the working directory it is running. This is to prevent other Snakemake processes to mess with the input/output files of the first process. In my use case, this feature prevents me to wrap SalmonTE in another Snakemake layer. To disable the locking mechanism, one can pass a command line parameter (`--nolock`), and [that's what I did in my fork](https://github.com/ftabaro/SalmonTE/blob/6acab8603c95926dc96d742d814ff06db0fe6e81/SalmonTE.py#L154). 

Now, I am not sure this behavior is desired and I am open for discussion. If you have other suggestions how to use SalmonTE in a Snakemake pipeline, I would be glad to hear.

**Comment by hyunhwaj** [comment]
@ftabaro, I want to make sure I understand it correctly, do you mean running SalmonTE disrupt other snakemake runs, even the other runs do not touch any files that are locked by SalmonTE?

Hyun-Hwan Jeong

**Comment by ftabaro** [comment]
The other way. SalmonTE fails to start because it finds the lock of the outer pipeline.

**Comment by hyunhwaj** [comment]
Got it, but I don't think a file being touched by multiple snakemakes simultaneously would be necessary and safe. Other thoughts?

Thank you,

Hyun-Hwan Jeong

**Comment by ftabaro** [comment]
One option could be to support Snakemake's `--unlock` option from SalmonTE top level scripts: e.g. `salmonTE quant [...] --no-lock`
