### ISSUE TITLE
why not integer with --exprtype=count option?

### ISSUE THREAD

**Issue by Xiaofei-git** [hyunhwan-jeong/SalmonTE#62]
Hi @hyunhwan-jeong , It is highly recommended to set --exprtype=count for differential expression analysis. But, I have question about the output. Why it is not integer for the counts as below for example? Thanks!

<img width="296" alt="Screen Shot 2021-12-01 at 10 37 12 AM" src="https://user-images.githubusercontent.com/22894969/144161870-73d73858-5655-470a-9fbd-f4a0face71e0.png">

**Comment by hyunhwan-jeong** [comment]
Hi @Xiaofei-git, this is duplicated with #23. In sum, the count mode would generate 'estimated count' as [Salmon did](https://salmon.readthedocs.io/en/latest/file_formats.html). You may need to round the numbers up for your next step. 

Thank you,

Hyun-Hwan Jeong

**Comment by Xiaofei-git** [comment]
> Hi @Xiaofei-git, this is duplicated with #23. In sum, the count mode would generate 'estimated count' as [Salmon did](https://salmon.readthedocs.io/en/latest/file_formats.html). You may need to round the numbers up for your next step.
> 
> Thank you,
> 
> Hyun-Hwan Jeong

Thanks, @hyunhwan-jeong !
