### ISSUE TITLE
coordinates of the TEs in clades.csv

### ISSUE THREAD

**Issue by Xiaofei-git** [hyunhwan-jeong/SalmonTE#63]
Hi @hyunhwan-jeong ,

How can I get the coordinates of the TEs in clades.csv. What is the reference version you used for mapping? I checked the salmonTE.py, but I did't find out.

The idea is to compare the expression of the TEs to the expression of neighboring genes, so I need to know the poison of TEs and the version of reference. 

Thanks a lot!

**Comment by hyunhwan-jeong** [comment]
Hello @Xiaofei-git,

SalmonTE doesn't provide any locus information of TEs. You may think about using some database like RepeatMasker/dfam to find the locations. If you think it would be useful to include those types of information in SalmonTE, I would be welcome to hear your idea.

Kind regards,

Hyun-Hwan Jeong

**Comment by Xiaofei-git** [comment]
I will try to figure it out and let you know. Thanks for your reply!
