### ISSUE TITLE
"Non-supported" species

### ISSUE THREAD

**Issue by amitjavilaventura** [hyunhwan-jeong/SalmonTE#64]
Dear Hyun-Hwan Jeong, 

I want to try salmonTE with species that are not in the supported ones (according to the documentation: _mm_, _hg_, _dr_ and _dm_). 

I was wondering whether I can build indexes for these species and use those for subsequent analyses. They are not present in RepBase, but I can download the repeat masker sequences (all TEs) from the UCSC. 

Is it possible to do this?

Thank you in advance.

Best regards,
Adrià.

**Comment by hyunhwan-jeong** [comment]
Sorry for the late response, @amitjavilaventura. I wonder you have finished creating the reference file - if you don't please describe that what species you want to try to build a reference.

Thank you,

Hyun-Hwan Jeong
