### ISSUE TITLE
 job execution failed --one of the commands exited with non-zero exit code

### ISSUE THREAD

**Issue by lgallegovillar** [hyunhwan-jeong/SalmonTE#65]
Hi @hyunhwan-jeong ,

I got the following error after running SalmonTE with a new reference index, hope you can help me with this. 

thanks, 
Lorena

System: 5.13.0-28-generic x86_64 bits: 64 compiler: N/A 
CPU: AMD Ryzen 7 4800U
Snakemake version: 6.15.5

lorena@Churribuntu:~/SalmonTE$ python3 SalmonTE.py quant --reference=hs_index --outpath=output_JMML_nindex/ example/CTRL_1_R1.fastq example/CTRL_1_R2.fastq  
2022-02-14 07:40:37,228 Starting quantification mode
2022-02-14 07:40:37,228 Collecting FASTQ files...
2022-02-14 07:40:37,230 The input dataset is considered as a paired-ends dataset.
2022-02-14 07:40:37,230 Collected 1 FASTQ files.
2022-02-14 07:40:37,231 Quantification has been finished.
2022-02-14 07:40:37,231 Running Salmon using Snakemake
Job stats:
job                    count    min threads    max threads
-------------------  -------  -------------  -------------
all                        1              1              1
collect_abundance          1              1              1
collect_mappability        1              1              1
run_salmon_fq              1              1              1
total                      4              1              1

2022-02-14 07:40:37,782 Job stats:
job                    count    min threads    max threads
-------------------  -------  -------------  -------------
all                        1              1              1
collect_abundance          1              1              1
collect_mappability        1              1              1
run_salmon_fq              1              1              1
total                      4              1              1

/usr/bin/bash: line 1: 141180 Killed                  salmon/linux/bin/salmon quant -q -i reference/hs_index -l A -1 /tmp/tmpmp16eaic/CTRL_1_R1.fastq -2 /tmp/tmpmp16eaic/CTRL_1_R2.fastq -o output_JMML_nindex/CTRL_1 -p 4 2> /dev/null
[Mon Feb 14 13:40:15 2022]
2022-02-14 13:40:15,892 [Mon Feb 14 13:40:15 2022]
Error in rule run_salmon_fq:
    jobid: 2
    output: output_JMML_nindex/CTRL_1
    shell:
        salmon/linux/bin/salmon quant -q -i reference/hs_index -l A -1 /tmp/tmpmp16eaic/CTRL_1_R1.fastq -2 /tmp/tmpmp16eaic/CTRL_1_R2.fastq -o output_JMML_nindex/CTRL_1 -p 4 2>/dev/null
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

2022-02-14 13:40:17,127 Error in rule run_salmon_fq:
    jobid: 2
    output: output_JMML_nindex/CTRL_1
    shell:
        salmon/linux/bin/salmon quant -q -i reference/hs_index -l A -1 /tmp/tmpmp16eaic/CTRL_1_R1.fastq -2 /tmp/tmpmp16eaic/CTRL_1_R2.fastq -o output_JMML_nindex/CTRL_1 -p 4 2>/dev/null
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Exiting because a job execution failed. Look above for error message
2022-02-14 13:40:21,174 Exiting because a job execution failed. Look above for error message
Traceback (most recent call last):
  File "SalmonTE.py", line 292, in <module>
    run(args)
  File "SalmonTE.py", line 243, in run
    run_salmon(param)
  File "SalmonTE.py", line 156, in run_salmon
    with open(os.path.join(param["--outpath"], "EXPR.csv" ), "r") as inp:
FileNotFoundError: [Errno 2] No such file or directory: 'output_JMML_nindex/EXPR.csv'

Thanks, 
Lorena

**Comment by hyunhwan-jeong** [comment]
@lgallegovillar, are you still facing the issue? If so, could you share an error message when you put the following command line `./salmon/linux/bin/salmon quant -q -i reference/hs_index -l A -1 /tmp/tmpmp16eaic/CTRL_1_R1.fastq -2 /tmp/tmpmp16eaic/CTRL_1_R2.fastq -o output_JMML_nindex/CTRL_1 -p 4 2> /dev/null` at the SalmonTE folder?

**Comment by hyunhwan-jeong** [comment]
Close due to no response
