### ISSUE TITLE
Syntax error in SalmonTE.py 

### ISSUE THREAD

**Issue by aditigopalan** [hyunhwan-jeong/SalmonTE#66]
When I run the following command: 
$ python3 SalmonTE.py quant --reference=hs example

I get this error:
  File "SalmonTE.py", line 7
    <!DOCTYPE html>
    ^

How do I fix this?

**Comment by hyunhwan-jeong** [comment]
@aditigopalan, this is a rare error, and I want you to check whether `SalmonTE.py` is modified. Can you check its md5sum? You are expect to see `d06954b1ca6a402837b6b2ac9464d488`. 

Thank you,

Hyun-Hwan Jeong

**Comment by hyunhwan-jeong** [comment]
Close due to no response.
