### ISSUE TITLE
Human fasta reference

### ISSUE THREAD

**Issue by smanessi** [hyunhwan-jeong/SalmonTE#71]
Hi,

I try to make a human custom reference.fa for SalmonTE. On github i found only mm.fa for mouse sample. 

I would like to check hs.fa either, where i can find it?
Thanks

**Comment by hyunhwan-jeong** [comment]
Hi @smanessi, please find at https://github.com/hyunhwan-jeong/SalmonTE/blob/master/scripts/hs_origin.fa

Best regards,

Hyun-Hwan Jeong
