### ISSUE TITLE
Why the results of quant mode are not integer?

### ISSUE THREAD

**Issue by gxAlan233** [hyunhwan-jeong/SalmonTE#72]
I used the quant mode (exprtype is count) but I found that the results are not integer so it could not be used in some packages in R.
If the exprtype is raw count, it should come out as integer, right?

Some of my results are as following:

TE | sample1 | sample2 | sample3
-- | -- | -- | --
ALU | 1161.53 | 1069.54 | 1230.75
AluJb | 1652.24 | 1277.59 | 1612.31
AluJo | 305.976 | 211.666 | 111.345
AluJr | 167.593 | 258.337 | 120.824
AluJr4 | 317.785 | 345.129 | 444.774
AluSc | 5873.77 | 5024.22 | 6805.05
AluSc5 | 1200.61 | 2001.05 | 2773.98

**Comment by rargelaguet** [comment]
I have the same question :)

**Comment by hyunhwan-jeong** [comment]
Sorry for the late response. This is related to #23 and #62. My answer is that SalmonTE uses `salmon` as a core algorithm for the quantification, and quantification is indeed an estimation of both raw counts/TPM. Thus, you can expect to see any floating numbers, and I'd recommend `rounding` the numbers for your downstream analysis.

Hope it helps,

Hyun-Hwan Jeong
